server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/quan_ly_de_tai_nghien_cuu?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false