server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_thesis?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=                    # ← ĐỂ TRỐNG, KHÔNG CÓ GÌ CẢ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.thymeleaf.cache=false